permalink: /:title

title: HXY|三十年来尘与土
url: http://huxingyu.top
feed: /atom.xml
author_info: <a href="http://huxingyu.top/">Huxingyu</a>
name: "Blog · Xingyu Hu"
description: "文字来自胡行宇，记录学习与生活的一点可记录的东西"
url: "http://huxingyu.top"
